M48
; DRILL file {KiCad 8.0.5} date 2025-10-02T23:06:01-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-02T23:06:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.9699Y-3.632
T2
X3.92Y-2.72
X3.92Y-4.06
X6.14Y-2.72
X6.14Y-4.06
M30
